[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
restaurant_protocol = "99vazimgMSgqzg3zLBGXhZjSZVBRvThChw49VVp9U39T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/matt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
